version: '3.8'
services:
  # starter-db:
  #   image: mysql:latest
  #   container_name: starter-api
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=starter
  #     - TZ=Asia/Bangkok
  # php my admin
  # starter-pma:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: starter-pma
  #   environment:
  #     - PMA_HOST=starter-db
  #     - PMA_USER=root
  #     - PMA_PASSWORD=root
  #   ports:
  #     - "8082:80"
  # postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:


